### ISSUE TITLE
Add timestamp and email to digital sign

### ISSUE THREAD

**Issue by alver-cliqz** [cliqz/browser-f#10]
Let's add at least timestamp to digital signes. Email could not be possible to add (i don't remember correctly, but it may be taken from certificate information)

**Comment by chrmod-cliqz** [comment]
Solved by https://github.com/cliqz/browser-f/commit/880efd555a4ec47cf4f042b571c56eb52fef014b

**Comment by chrmod-cliqz** [comment]
Could not find a way to set email. It seems it is being provided by certificate.
